cleaned up post install script, moved broken emacs theme config to it's own script for now

diff --git a/post_install b/post_install
--- a/post_install
+++ b/post_install
@@ -11,24 +11,16 @@ if [ "$(echo $SHELL)" != "/bin/bash" ]; then
   fi
 fi
 
-# add progress message for unofficial repo
-echo "Adding unofficial repo for emacs v28..."
-sudo apt-get update > /dev/null || { echo "Failed to update packages"; exit 1; }
-#sudo apt-get install software-properties-common -y > /dev/null || { echo "Failed to install software-properties-common"; exit 1; }
-sudo add-apt-repository -y ppa:kelleyk/emacs > /dev/null || { echo "Failed to add unofficial repo"; exit 1; }
-
 # System Update and Upgrade
 echo "Updating system packages..."
 sudo apt-get update > /dev/null || { echo "Failed to update packages"; exit 1; }
-#sudo apt-get install --fix-missing -y > /dev/null || { echo "Failed to install missing packages"; exit 1; }
 sudo apt-get upgrade --allow-downgrades -y > /dev/null || { echo "Failed to upgrade packages"; exit 1; }
-
-#kill any instances of emacs that are running
-pkill emacs
+echo "installing software-properties-common package"
+sudo apt-get install software-properties-common -y > /dev/null || { echo "Failed to install software-properties-common"; exit 1; }
 
 #install essential apps
 echo "Installing essential apps..."
-sudo apt-get install -y curl git gcc make wget emacs28 python3 python3-pip htop openssh-client rsync netcat > /dev/null || { echo "Failed to install essential apps"; exit 1; }
+sudo apt-get install -y curl git gcc make wget emacs python3 python3-pip htop openssh-client rsync netcat > /dev/null || { echo "Failed to install essential apps"; exit 1; }
 
 # Check if .bashrc file exists
 if [ ! -e ~/.bashrc ]; then
